services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - /opt/grafana:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=https://grafana.example/
      - GF_SECURITY_ADMIN_PASSWORD=secret
    restart:
      unless-stopped

  kpi-api:
    image: ghcr.io/qberal/kpi-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart:
      unless-stopped